"""Canned sample content for the top-bar "demo state" switcher.

The switcher exists purely to preview the four shell states (Empty / Ready /
Generated / Error) without needing a real file on disk — handy for visual
QA and for the screenshots in the design spec. It never touches real parsed
data; ui/main_window.py always prefers real state once the user performs a
real action (selecting a file, generating, copying, saving).
"""
from __future__ import annotations

DEMO_FILE_NAME = "survey_points_east.txt"
DEMO_POINTS_COUNT = 128
DEMO_FILE_SIZE = "42 KB"

DEMO_SCRIPT_TEXT = """;; AutoCAD Script — generated by Script Generator PRO
;; Source: survey_points_east.txt · 128 points
-LAYER
Set 0
-3DPOLY
512340.120,4519823.440,102.30
512341.880,4519825.110,102.55
512343.220,4519826.760,102.61
;; …125 more points"""

DEMO_ERROR_MESSAGE = (
    "Line 47: expected 3 numeric columns (number, X, Y[, H]) but found 2 — "
    "check the Source & Delimiter setting."
)
